[tool.poetry]
name = "mcp-server"
version = "0.1.0"
description = "MCP Server"
authors = ["MCP <mcp@example.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
uvicorn = "^0.28.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api" 